from numpy import *
a=[[1,2,3],[4,5,6]]
b=matrix(a)
print(type(b))
print(type(a))
str='1 2;3 4;5 6'
print(type(str))
b=matrix(str)
print(type(b))
i=arange(1,10,1).reshape(3,3)
print(i)
d=diagonal(i)
print('diagonal elements are',d)
big=i.max()
print('big one is',big)
small=i.min()
print('small element is',small)
print('sum is',i.sum())
print('mean is',i.mean())
colu=i.prod(0)
print('colum product',colu)
row=i.prod(1)
print('row product',row)
t=i.transpose()
print('transpose of matrix',t)
sort=sort(t,axis=1)
print('sort',sort)
